In [90]:
 # Part 1: Dataset Creation

import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


# Part 2: Basic Array Understanding

In [91]:
# Question 1: Array Dimensions

import numpy as np

print("Number of dimensions (ndim):", sales_data.ndim)
print("Shape:", sales_data.shape)
print("Total number of values (size):", sales_data.size)
print("Data type (dtype):", sales_data.dtype)
print("Memory occupied (nbytes):", sales_data.nbytes, "bytes")

Number of dimensions (ndim): 2
Shape: (5, 6)
Total number of values (size): 30
Data type (dtype): int64
Memory occupied (nbytes): 240 bytes


In [92]:
# Question 2: Store and Category Count

total_stores = sales_data.shape[0]
total_categories = sales_data.shape[1]
total_combinations = sales_data.size

print("Total number of stores:", total_stores)
print("Total number of product categories:", total_categories)
print("Total number of store-category combinations:", total_combinations)

Total number of stores: 5
Total number of product categories: 6
Total number of store-category combinations: 30


In [93]:
# Question 3: Sales Data Type Conversion.

sales_float32 = sales_data.astype(np.float32)
sales_float64 = sales_data.astype(np.float64)

print("Memory used by original (int) array:", sales_data.nbytes, "bytes")
print("Memory used by float32 array:", sales_float32.nbytes, "bytes")
print("Memory used by float64 array:", sales_float64.nbytes, "bytes")

Memory used by original (int) array: 240 bytes
Memory used by float32 array: 120 bytes
Memory used by float64 array: 240 bytes


# Part 3: Indexing and Data Extraction

In [94]:
# Question 4: Bengaluru Store Analysis.

bengaluru_sales = sales_data[0]
print("Bengaluru sales (all categories):", bengaluru_sales)

Bengaluru sales (all categories): [850000 420000 310000 275000 190000 225000]


In [95]:
# Question 5: Mumbai Cost Analysis.

mumbai_cost = cost_data[3]
print("Mumbai cost (all categories):", mumbai_cost)

Mumbai cost (all categories): [790000 390000 265000 250000 165000 205000]


In [96]:
# Question 6: Electronics Sales Across Stores.

electronics_sales = sales_data[:, 0]
print("Electronics sales across all stores:", electronics_sales)

Electronics sales across all stores: [ 850000  780000  920000 1050000  690000]


In [97]:
# Question 7: Clothing Cost Across Stores.

clothing_cost = cost_data[:, 2]
print("Clothing cost across all stores:", clothing_cost)

Clothing cost across all stores: [220000 210000 245000 265000 205000]


In [98]:
# Question 8: Hyderabad Furniture Performance.

hyd_furniture_sales = sales_data[1, 3]
hyd_furniture_cost = cost_data[1, 3]
hyd_furniture_profit = hyd_furniture_sales - hyd_furniture_cost

print("Hyderabad Furniture Sales:", hyd_furniture_sales)
print("Hyderabad Furniture Cost:", hyd_furniture_cost)
print("Hyderabad Furniture Profit:", hyd_furniture_profit)

Hyderabad Furniture Sales: 310000
Hyderabad Furniture Cost: 225000
Hyderabad Furniture Profit: 85000


In [99]:
# Question 9: Chennai Category Range.

chennai_range = sales_data[2, 1:4]
print("Chennai sales [Groceries, Clothing, Furniture]:", chennai_range)


Chennai sales [Groceries, Clothing, Furniture]: [390000 340000 260000]


In [100]:
# Question 10: Selected Store Analysis.

store_idx = [0, 2, 4]
category_idx = [0, 2, 4]

selected_data = sales_data[np.ix_(store_idx, category_idx)]
print("Stores:", stores[store_idx])
print("Categories:", categories[category_idx])
print(selected_data)

Stores: ['Bengaluru' 'Chennai' 'Pune']
Categories: ['Electronics' 'Clothing' 'Beauty']
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


# Part 4: Sales Aggregation

In [101]:
# Question 11: Company-Wide Sales.

total_sales = np.sum(sales_data)
print("Total company-wide sales revenue:", total_sales)


Total company-wide sales revenue: 11675000


In [102]:
# Question 12: Store-Wise Sales.

store_wise_sales = np.sum(sales_data, axis=1)

for store, total in zip(stores, store_wise_sales):
    print(f"{store}: {total}")

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


In [103]:
# Question 13: Category-Wise Sales

category_wise_sales = np.sum(sales_data, axis=0)

for cat, total in zip(categories, category_wise_sales):
    print(f"{cat}: {total}")

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Beauty: 1010000
Sports: 1175000


In [104]:
# Question 14: Average Sales Per Store.

avg_sales_per_store = np.mean(sales_data, axis=1)

for store, avg in zip(stores, avg_sales_per_store):
    print(f"{store}: {avg:.2f}")

Bengaluru: 378333.33
Hyderabad: 382500.00
Chennai: 385000.00
Mumbai: 470000.00
Pune: 330000.00


In [105]:
# Question 15: Average Sales Per Category.

avg_sales_per_category = np.mean(sales_data, axis=0)

for cat, avg in zip(categories, avg_sales_per_category):
    print(f"{cat}: {avg:.2f}")

Electronics: 858000.00
Groceries: 437000.00
Clothing: 320000.00
Furniture: 283000.00
Beauty: 202000.00
Sports: 235000.00


In [106]:
# Question 16: Highest-Selling Store.

store_wise_sales = np.sum(sales_data, axis=1)

top_store_idx = np.argmax(store_wise_sales)
print("Index:", top_store_idx)
print("Store name:", stores[top_store_idx])
print("Total sales:", store_wise_sales[top_store_idx])

Index: 3
Store name: Mumbai
Total sales: 2820000


In [107]:
# Question 17: Lowest-Selling Store.

store_wise_sales = np.sum(sales_data, axis=1)

low_store_idx = np.argmin(store_wise_sales)
print("Index:", low_store_idx)
print("Store name:", stores[low_store_idx])
print("Total sales:", store_wise_sales[low_store_idx])


Index: 4
Store name: Pune
Total sales: 1980000


In [108]:
# Question 18: Highest-Selling Category.

category_wise_sales = np.sum(sales_data, axis=0)

top_cat_idx = np.argmax(category_wise_sales)
print("Index:", top_cat_idx)
print("Category name:", categories[top_cat_idx])
print("Total sales:", category_wise_sales[top_cat_idx])

Index: 0
Category name: Electronics
Total sales: 4290000


In [109]:
# Question 19: Lowest-Selling Category.

category_wise_sales = np.sum(sales_data, axis=0)

low_cat_idx = np.argmin(category_wise_sales)
print("Index:", low_cat_idx)
print("Category name:", categories[low_cat_idx])
print("Total sales:", category_wise_sales[low_cat_idx])

Index: 4
Category name: Beauty
Total sales: 1010000


In [110]:
# Question 20: Total Company Cost.

total_cost = np.sum(cost_data)
print("Total company-wide cost:", total_cost)

Total company-wide cost: 8600000


# Part 5: Cost Analysis

In [111]:
# Question 21: Store-Wise Cost.

store_wise_cost = np.sum(cost_data, axis=1)

for store, total in zip(stores, store_wise_cost):
    print(f"{store}: {total}")


Bengaluru: 1665000
Hyderabad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000


In [112]:
# Question 22: Category-Wise Cost.

category_wise_cost = np.sum(cost_data, axis=0)

for cat, total in zip(categories, category_wise_cost):
    print(f"{cat}: {total}")

Electronics: 3250000
Groceries: 1660000
Clothing: 1145000
Furniture: 1045000
Beauty: 665000
Sports: 835000


In [113]:
# Question 23: Most Expensive Store.

store_wise_cost = np.sum(cost_data, axis=1)

top_cost_idx = np.argmax(store_wise_cost)
print("Index:", top_cost_idx)
print("Store name:", stores[top_cost_idx])
print("Total cost:", store_wise_cost[top_cost_idx])

Index: 3
Store name: Mumbai
Total cost: 2065000


In [114]:
# Question 24: Lowest-Cost Store.

store_wise_cost = np.sum(cost_data, axis=1)

low_cost_idx = np.argmin(store_wise_cost)
print("Index:", low_cost_idx)
print("Store name:", stores[low_cost_idx])
print("Total cost:", store_wise_cost[low_cost_idx])

Index: 4
Store name: Pune
Total cost: 1475000


In [115]:
# Question 25: Most Expensive Product Category.

category_wise_cost = np.sum(cost_data, axis=0)

top_cost_cat_idx = np.argmax(category_wise_cost)
print("Index:", top_cost_cat_idx)
print("Category name:", categories[top_cost_cat_idx])
print("Total cost:", category_wise_cost[top_cost_cat_idx])

Index: 0
Category name: Electronics
Total cost: 3250000


In [116]:
# Question 26: Profit Matrix.

profit_data = sales_data - cost_data
print("Profit Matrix:")
print(profit_data)

Profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [117]:
# Question 27: Store-Wise Profit.

store_wise_profit = np.sum(profit_data, axis=1)

for store, total in zip(stores, store_wise_profit):
    print(f"{store}: {total}")

Bengaluru: 605000
Hyderabad: 610000
Chennai: 600000
Mumbai: 755000
Pune: 505000


In [118]:
# Question 28: Category-Wise Profit.

category_wise_profit = np.sum(profit_data, axis=0)

for cat, total in zip(categories, category_wise_profit):
    print(f"{cat}: {total}")

Electronics: 1040000
Groceries: 525000
Clothing: 455000
Furniture: 370000
Beauty: 345000
Sports: 340000


In [119]:
# Question 29: Most Profitable Store.

store_wise_profit = np.sum(profit_data, axis=1)

top_profit_idx = np.argmax(store_wise_profit)
print("Store name:", stores[top_profit_idx])
print("Total sales:", store_wise_sales[top_profit_idx])
print("Total cost:", store_wise_cost[top_profit_idx])
print("Total profit:", store_wise_profit[top_profit_idx])

Store name: Mumbai
Total sales: 2820000
Total cost: 2065000
Total profit: 755000


In [120]:
# Question 30: Least Profitable Store.

store_wise_profit = np.sum(profit_data, axis=1)

low_profit_idx = np.argmin(store_wise_profit)
print("Store name:", stores[low_profit_idx])
print("Total profit:", store_wise_profit[low_profit_idx])


Store name: Pune
Total profit: 505000


In [121]:
# Question 31: Most Profitable Category.

category_wise_profit = np.sum(profit_data, axis=0)

top_cat_profit_idx = np.argmax(category_wise_profit)
print("Category name:", categories[top_cat_profit_idx])
print("Total profit:", category_wise_profit[top_cat_profit_idx])

Category name: Electronics
Total profit: 1040000


In [122]:
# Question 32: Least Profitable Category.

low_cat_profit_idx = np.argmin(category_wise_profit)
print("Category name:", categories[low_cat_profit_idx])
print("Total profit:", category_wise_profit[low_cat_profit_idx])

Category name: Sports
Total profit: 340000


In [123]:
# Question 33: Maximum Individual Profit.

max_flat_idx = np.argmax(profit_data)
max_row, max_col = np.unravel_index(max_flat_idx, profit_data.shape)

print("Profit amount:", profit_data[max_row, max_col])
print("Store name:", stores[max_row])
print("Product category:", categories[max_col])

Profit amount: 260000
Store name: Mumbai
Product category: Electronics


In [124]:
# Question 34: Minimum Individual Profit.

min_flat_idx = np.argmin(profit_data)
min_row, min_col = np.unravel_index(min_flat_idx, profit_data.shape)

print("Profit amount:", profit_data[min_row, min_col])
print("Store name:", stores[min_row])
print("Product category:", categories[min_col])

Profit amount: 55000
Store name: Pune
Product category: Furniture


# Part 7: Profit Margin Analysis

In [125]:
# Question 35: Profit Margin Matrix.

profit_margin = (profit_data / sales_data) * 100
profit_margin = np.round(profit_margin, 2)
print(profit_margin)

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [126]:
# Question 36: Store-Wise Profit Margin.

store_wise_sales = np.sum(sales_data, axis=1)
store_wise_profit = np.sum(profit_data, axis=1)
store_profit_margin = np.round((store_wise_profit / store_wise_sales) * 100, 2)

for store, margin in zip(stores, store_profit_margin):
    print(f"{store}: {margin}%")

Bengaluru: 26.65%
Hyderabad: 26.58%
Chennai: 25.97%
Mumbai: 26.77%
Pune: 25.51%


In [127]:
# Question 37: Category-Wise Profit Margin.

category_wise_sales = np.sum(sales_data, axis=0)
category_wise_profit = np.sum(profit_data, axis=0)
category_profit_margin = np.round((category_wise_profit / category_wise_sales) * 100, 2)

for cat, margin in zip(categories, category_profit_margin):
    print(f"{cat}: {margin}%")

Electronics: 24.24%
Groceries: 24.03%
Clothing: 28.44%
Furniture: 26.15%
Beauty: 34.16%
Sports: 28.94%


In [128]:
# Question 38: Best Store by Profit Margin.
best_margin_idx = np.argmax(store_profit_margin)
print("Store name:", stores[best_margin_idx])
print("Profit margin:", store_profit_margin[best_margin_idx], "%")

Store name: Mumbai
Profit margin: 26.77 %


In [129]:
# Question 39: Best Category by Profit Margin.

best_cat_margin_idx = np.argmax(category_profit_margin)
print("Category name:", categories[best_cat_margin_idx])
print("Profit margin:", category_profit_margin[best_cat_margin_idx], "%")

Category name: Beauty
Profit margin: 34.16 %


In [130]:
# Question 40: Low-Margin Transactions.

mask = profit_margin < 22

row_idx, col_idx = np.where(mask)

if len(row_idx) == 0:
    print("No store-category combinations found with profit margin below 22%.")
    print("Minimum profit margin in the dataset:", np.min(profit_margin), "%")
else:
    for r, c in zip(row_idx, col_idx):
        print(f"Store: {stores[r]}, Category: {categories[c]}, "
              f"Sales: {sales_data[r,c]}, Cost: {cost_data[r,c]}, "
              f"Profit: {profit_data[r,c]}, Margin: {profit_margin[r,c]}%")

No store-category combinations found with profit margin below 22%.
Minimum profit margin in the dataset: 23.19 %


# Part 8: Boolean Filtering

In [131]:
# Question 41: High Sales Values.

high_sales_mask = sales_data > 500000
print(sales_data[high_sales_mask])

[ 850000  780000  920000 1050000  510000  690000]


In [132]:
# Question 42: Low Sales Values.

low_sales_mask = sales_data < 200000
print(sales_data[low_sales_mask])

[190000 185000 175000]


In [133]:
# Question 43: High Profit Values.

high_profit_mask = profit_data > 150000
r_idx, c_idx = np.where(high_profit_mask)
for r, c in zip(r_idx, c_idx):
    print(f"{stores[r]} - {categories[c]}: {profit_data[r,c]}")

Bengaluru - Electronics: 210000
Hyderabad - Electronics: 190000
Chennai - Electronics: 220000
Mumbai - Electronics: 260000
Pune - Electronics: 160000


In [134]:
# Question 44: Moderate Sales Range.

moderate_mask = np.logical_and(sales_data >= 250000, sales_data <= 500000)
print(sales_data[moderate_mask])

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


In [135]:
# Question 45: Premium Performance.

premium_mask = np.logical_and(sales_data > 500000, profit_data > 150000)
r_idx, c_idx = np.where(premium_mask)
for r, c in zip(r_idx, c_idx):
    print(f"{stores[r]} - {categories[c]}: Sales={sales_data[r,c]}, Profit={profit_data[r,c]}")


Bengaluru - Electronics: Sales=850000, Profit=210000
Hyderabad - Electronics: Sales=780000, Profit=190000
Chennai - Electronics: Sales=920000, Profit=220000
Mumbai - Electronics: Sales=1050000, Profit=260000
Pune - Electronics: Sales=690000, Profit=160000


In [136]:
# Question 46: Underperforming Combinations.

under_mask = np.logical_and(sales_data < 250000, profit_margin < 25)
r_idx, c_idx = np.where(under_mask)
for r, c in zip(r_idx, c_idx):
    print(f"{stores[r]} - {categories[c]}: Sales={sales_data[r,c]}, Margin={profit_margin[r,c]}%")

Pune - Furniture: Sales=225000, Margin=24.44%


In [137]:
# Question 47: Category Performance Classification.

conditions = [
    sales_data >= 500000,
    (sales_data >= 250000) & (sales_data < 500000)
]
choices = ['High', 'Medium']
classification = np.select(conditions, choices, default='Low')
print(classification)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


# Part 9: Target-Based Analysis

In [138]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

In [139]:
# Question 48: Target Comparison.

comparison = sales_data - sales_targets
print(comparison)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [140]:
# Question 49: Target Achievement Matrix.

achievement = sales_data >= sales_targets
print(achievement)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [141]:
# Question 50: Target Achievement Count.

achievement_count = np.sum(achievement, axis=1)
for store, cnt in zip(stores, achievement_count):
    print(f"{store}: {cnt} / 6")

Bengaluru: 1 / 6
Hyderabad: 4 / 6
Chennai: 2 / 6
Mumbai: 6 / 6
Pune: 0 / 6


In [142]:
# Question 51: Best Target-Performing Store.

best_idx = np.argmax(achievement_count)
print("Store name:", stores[best_idx])
print("Targets achieved:", achievement_count[best_idx])

Store name: Mumbai
Targets achieved: 6


In [143]:
# Question 52: Target Achievement by Category.

cat_achievement_count = np.sum(achievement, axis=0)
for cat, cnt in zip(categories, cat_achievement_count):
    print(f"{cat}: {cnt} / 5 stores")


Electronics: 3 / 5 stores
Groceries: 2 / 5 stores
Clothing: 2 / 5 stores
Furniture: 2 / 5 stores
Beauty: 2 / 5 stores
Sports: 2 / 5 stores


In [144]:
# Question 53: Sales Target Variance.

variance = sales_data - sales_targets
print(variance)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [145]:
# Question 54: Percentage Above or Below Target.

pct_variance = np.round((variance / sales_targets) * 100, 2)
print(pct_variance)

[[  6.25  -6.67  -3.12  -8.33  -5.    -2.17]
 [ -2.5    2.22  -7.81   3.33   5.     4.35]
 [ 15.   -13.33   6.25 -13.33  -7.5   -6.52]
 [ 31.25  13.33  17.19  15.    25.    26.09]
 [-13.75 -10.   -12.5  -25.   -12.5  -10.87]]


In [146]:
# Question 55: Stores Missing Electronics Target.

electronics_achieved = achievement[:, 0]
missing_electronics = stores[~electronics_achieved]
print(missing_electronics)

['Hyderabad' 'Pune']


In [147]:
# Question 56: Stores Achieving All Targets.

all_targets_met = np.all(achievement, axis=1)
stores_all_met = stores[all_targets_met]
print(stores_all_met)

['Mumbai']


In [148]:
# Question 57: Stores Achieving At Least One Target.

any_target_met = np.any(achievement, axis=1)
stores_any_met = stores[any_target_met]
print(stores_any_met)

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


# Part 10: Discount Scenario

In [149]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [150]:
# Question 58: Discount Amount Matrix.

discount_amount = sales_data * discount_rates
print(discount_amount)


[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


In [151]:
# Question 59: Sales After Discount.

sales_after_discount = sales_data - discount_amount
print(sales_after_discount)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


In [152]:
# Question 60: Profit After Discount.

profit_after_discount = sales_after_discount - cost_data
print(profit_after_discount)

[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


In [153]:
# Question 61: Profit Margin After Discount.

profit_margin_after = np.round((profit_after_discount / sales_after_discount) * 100, 2)
print(profit_margin_after)

[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


In [154]:
# Question 62: Loss-Making Transactions.

loss_mask = profit_after_discount < 0
r_idx, c_idx = np.where(loss_mask)

if len(r_idx) == 0:
    print("No store-category combination becomes loss-making after discounts.")

No store-category combination becomes loss-making after discounts.


In [155]:
# Question 63: Discount Impact.\

total_discount_impact = np.sum(discount_amount)
print("Total revenue lost to discounts:", total_discount_impact)


Total revenue lost to discounts: 1146350.0


In [156]:
# Question 64: Store Most Affected by Discounts.

store_wise_discount = np.sum(discount_amount, axis=1)
most_affected_idx = np.argmax(store_wise_discount)
print("Most affected store:", stores[most_affected_idx])
print("Loss:", store_wise_discount[most_affected_idx])

Most affected store: Mumbai
Loss: 277150.0


# Part 11: Tax and Price Adjustment

In [157]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

In [158]:
# Question 65: Tax Collection Matrix.

tax_amount = sales_data * tax_rates
print(tax_amount)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


In [159]:
# Question 66: Sales Including Tax.

sales_with_tax = sales_data + tax_amount
print(sales_with_tax)

[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


In [160]:
# Question 67: Store-Wise Tax Collection.

store_wise_tax = np.sum(tax_amount, axis=1)
for store, amt in zip(stores, store_wise_tax):
    print(f"{store}: {amt:.2f}")


Bengaluru: 321900.00
Hyderabad: 321200.00
Chennai: 331800.00
Mumbai: 401400.00
Pune: 274650.00


In [161]:
# Question 68: Category-Wise Tax Collection.

category_wise_tax = np.sum(tax_amount, axis=0)
for cat, amt in zip(categories, category_wise_tax):
    print(f"{cat}: {amt:.2f}")


Electronics: 772200.00
Groceries: 109250.00
Clothing: 192000.00
Furniture: 254700.00
Beauty: 181800.00
Sports: 141000.00


In [162]:
# Question 69: Highest Tax-Contributing Store.

top_tax_idx = np.argmax(store_wise_tax)
print("Store name:", stores[top_tax_idx])
print("Total tax:", store_wise_tax[top_tax_idx])

Store name: Mumbai
Total tax: 401400.0


# Part 12: Array Modification

In [163]:
# Question 70: Updated Pune Electronics Sales.

sales_data_copy = sales_data.copy()
sales_data_copy[4, 0] = 740000

print("Original (unchanged):", sales_data[4,0])
print("Copy (updated):", sales_data_copy[4,0])

Original (unchanged): 690000
Copy (updated): 740000


In [164]:
# Question 71: Revised Beauty Cost.

cost_data_v2 = cost_data.copy()
cost_data_v2[:, 4] = cost_data_v2[:, 4] * 0.92

print(cost_data_v2)

[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


In [165]:
# Question 72: Furniture Cost Increase.

cost_data_v3 = cost_data.copy()
cost_data_v3[:, 3] = cost_data_v3[:, 3] * 1.12

print(cost_data_v3)


[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


In [166]:
# Question 73: Store Closure Simulation.

import numpy as np

store_names = np.array(['Mumbai', 'Pune', 'Delhi', 'Bangalore'])
sales = np.array([25000, 18000, 40000, 30000])
cost = np.array([15000, 11000, 22000, 17000])

pune_index = np.where(store_names == 'Pune')[0][0]

store_names = np.delete(store_names, pune_index)
sales = np.delete(sales, pune_index)
cost = np.delete(cost, pune_index)

print(store_names)
print(sales)
print(cost)


['Mumbai' 'Delhi' 'Bangalore']
[25000 40000 30000]
[15000 22000 17000]


In [167]:
# Question 74: Adding a New Store.

import numpy as np

stores = np.array(['Mumbai', 'Pune', 'Bangalore'])
sales_matrix = np.array([[100, 200], [150, 250], [300, 350]])

delhi_sales = np.array([400, 450])

sales_matrix = np.vstack([sales_matrix, delhi_sales])
stores = np.append(stores, "Delhi")

print(stores)
print(sales_matrix)


['Mumbai' 'Pune' 'Bangalore' 'Delhi']
[[100 200]
 [150 250]
 [300 350]
 [400 450]]


In [168]:
# Question 75: Adding a New Product Category.

import numpy as np

home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])

home_appliances = np.column_stack((home_appliance_sales, home_appliance_cost))

home_appliances = np.hstack((
    home_appliance_sales.reshape(-1, 1),
    home_appliance_cost.reshape(-1, 1)
))
print(home_appliances)

[[360000 265000]
 [325000 240000]
 [390000 285000]
 [420000 305000]
 [295000 225000]]


In [169]:
# Question 76: Sort Stores by Sales.

import numpy as np

store_names = np.array(["Store A", "Store B", "Store C", "Store D", "Store E"])
total_sales = np.array([5000, 2000, 8000, 3000, 6000])

sorted_indices = np.argsort(total_sales)

sorted_store_names = store_names[sorted_indices]
sorted_sales = total_sales[sorted_indices]

print("Stores sorted by Sales (Ascending Order):")
for name, sales in zip(sorted_store_names, sorted_sales):
    print(f"{name}: {sales}")

Stores sorted by Sales (Ascending Order):
Store B: 2000
Store D: 3000
Store A: 5000
Store E: 6000
Store C: 8000


In [170]:
# Question 77: Rank Stores by Profit.

import numpy as np

store_names = np.array(["Store A", "Store B", "Store C", "Store D", "Store E"])
total_profit = np.array([1200, 4500, 3000, 800, 2000])

sorted_indices_desc = np.argsort(total_profit)[::-1]


ranked_store_names = store_names[sorted_indices_desc]
ranked_profits = total_profit[sorted_indices_desc]

print("Store Ranking by Profit (Highest to Lowest):")
for rank, (name, profit) in enumerate(zip(ranked_store_names, ranked_profits), start=1):
    print(f"Rank {rank}: {name} - Profit: {profit}")

Store Ranking by Profit (Highest to Lowest):
Rank 1: Store B - Profit: 4500
Rank 2: Store C - Profit: 3000
Rank 3: Store E - Profit: 2000
Rank 4: Store A - Profit: 1200
Rank 5: Store D - Profit: 800


In [171]:
# Question 78: Sort Categories by Revenue.

import numpy as np

category_names = np.array(["Electronics", "Groceries", "Clothing", "Furniture"])
category_revenue = np.array([15000, 22000, 9000, 12000])

sorted_indices_desc = np.argsort(category_revenue)[::-1]

sorted_category_names = category_names[sorted_indices_desc]
sorted_revenue = category_revenue[sorted_indices_desc]

print("Categories sorted by Revenue (Highest to Lowest):")
for name, revenue in zip(sorted_category_names, sorted_revenue):
    print(f"{name}: {revenue}")

Categories sorted by Revenue (Highest to Lowest):
Groceries: 22000
Electronics: 15000
Furniture: 12000
Clothing: 9000


In [172]:
# Question 79: Top Three Store-Category Sales.

import numpy as np

store_names = np.array(["Store A", "Store B", "Store C"])
category_names = np.array(["Electronics", "Groceries", "Clothing"])

sales_matrix = np.array([
    [500, 700, 300],   # Store A
    [900, 200, 600],   # Store B
    [400, 800, 1000]   # Store C
])

flat_sales = sales_matrix.flatten()

sorted_indices = np.argsort(flat_sales)

top_3_indices = sorted_indices[-3:][::-1]

top_3_positions = np.unravel_index(top_3_indices, sales_matrix.shape)

print("Top 3 Store-Category Sales:")
for rank, (row, col) in enumerate(zip(*top_3_positions), start=1):
    value = sales_matrix[row, col]
    print(f"Rank {rank}: {value} | Store: {store_names[row]} | Category: {category_names[col]}")

Top 3 Store-Category Sales:
Rank 1: 1000 | Store: Store C | Category: Clothing
Rank 2: 900 | Store: Store B | Category: Electronics
Rank 3: 800 | Store: Store C | Category: Groceries


In [176]:
# Question 80: Bottom Three Profits.

import numpy as np
store_names = np.array(["Store A", "Store B", "Store C"])
category_names = np.array(["Electronics", "Groceries", "Clothing"])

profit_matrix = np.array([
    [50, 120, 30],
    [90, 10, 60],
    [40, 80, 15]
])
flat_profit = profit_matrix.flatten()
sorted_indices = np.argsort(flat_profit)
bottom_3_indices = sorted_indices[:3]
bottom_3_positions = np.unravel_index(bottom_3_indices, profit_matrix.shape)
print("Bottom 3 Profits:")
for rank, (row, col) in enumerate(zip(*bottom_3_positions), start=1):
    value = profit_matrix[row, col]
    print(f"Rank {rank}: {value} | Store: {store_names[row]} | Category: {category_names[col]}")

Bottom 3 Profits:
Rank 1: 10 | Store: Store B | Category: Groceries
Rank 2: 15 | Store: Store C | Category: Clothing
Rank 3: 30 | Store: Store A | Category: Clothing


# Part 14: Statistical Analysis

In [178]:
# Question 82: Store-Wise Standard Deviation.

store_names = np.array(["Store A", "Store B", "Store C", "Store D"])

store_std = np.std(sales_data, axis=1)
print("Standard Deviation per Store:", store_std)
print("Store with Most Variation:", store_names[np.argmax(store_std)])

Standard Deviation per Store: [223059.53365762 194502.5706771  249265.58794453 271860.87128039
 177200.45146669]
Store with Most Variation: Store D


In [179]:
# Question 83: Category-Wise Standard Deviation.

category_names = np.array(["Electronics", "Groceries", "Clothing", "Furniture"])
category_std = np.std(sales_data, axis=0)
print("Category Std Dev:", category_std)
print("Most Variation Category:", category_names[np.argmax(category_std)])

Category Std Dev: [122539.78945632  43312.81565542  33911.64991563  41303.75285613
  26570.66051117  29832.86778035]
Most Variation Category: Electronics


In [180]:
# Question 84: Sales Above Company Average.

import numpy as np

company_avg = np.mean(sales_data)
count_above = np.sum(sales_data > company_avg)

print("Company Average Sales:", company_avg)
print("Values Above Average:", count_above)

Company Average Sales: 389166.6666666667
Values Above Average: 10


In [181]:
# Question 85: Outlier Detection.

import numpy as np

threshold = np.mean(sales_data) + 1.5 * np.std(sales_data)
outliers = sales_data[sales_data > threshold]

print("Outlier Threshold:", threshold)
print("High-Value Outliers:", outliers)

Outlier Threshold: 734650.4759833985
High-Value Outliers: [ 850000  780000  920000 1050000]


# Part 15: Reshaping and Transformation

In [182]:
# Question 86: Flatten Sales Data.

import numpy as np

flat1 = sales_data.flatten()
flat2 = sales_data.ravel()

print("Flatten:", flat1)
print("Ravel:", flat2)

Flatten: [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
Ravel: [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


In [185]:
# Question 88: Transpose Sales Data.

import numpy as np

transposed_sales = sales_data.T

print("Original Shape:", sales_data.shape)
print("Transposed Shape:", transposed_sales.shape)


Original Shape: (5, 6)
Transposed Shape: (6, 5)


# Part 16: Missing Data Scenario

In [189]:
# The company discovers that some sales values were not recorded.

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

In [190]:
# Question 91: Missing Value Detection

import numpy as np
total_missing = np.isnan(sales_data).sum()
print("Total Missing Values:", total_missing)
missing_rows, missing_cols = np.where(np.isnan(sales_data))
print("Missing Locations (row, col):", list(zip(missing_rows, missing_cols)))
print("Missing Locations (row, col):", list(zip(missing_rows, missing_cols)))
print("Stores with Missing Values:", np.unique(missing_rows))
print("Categories with Missing Values:", np.unique(missing_cols))

Total Missing Values: 0
Missing Locations (row, col): []
Missing Locations (row, col): []
Stores with Missing Values: []
Categories with Missing Values: []


In [191]:
# Question 92: Replace Missing Values with Zero.

import numpy as np

sales_data_filled = np.nan_to_num(sales_data, nan=0)

print("Sales Data with Missing Values as 0:\n", sales_data_filled)

Sales Data with Missing Values as 0:
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [192]:
# Question 93: Replace with Company Average.

import numpy as np

avg_value = np.nanmean(sales_data)
sales_data_filled = np.where(np.isnan(sales_data), avg_value, sales_data)

print("Company Average (ignoring NaNs):", avg_value)
print("Sales Data with Missing Values Replaced:\n", sales_data_filled)

Company Average (ignoring NaNs): 389166.6666666667
Sales Data with Missing Values Replaced:
 [[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]


In [193]:
# Question 94: Replace with Category Average.

import numpy as np

category_avg = np.nanmean(sales_data, axis=0)
inds = np.where(np.isnan(sales_data))
sales_data_filled = sales_data.copy()
sales_data_filled[inds] = np.take(category_avg, inds[1])

print("Category Averages:", category_avg)
print("Sales Data with Missing Values Replaced:\n", sales_data_filled)

Category Averages: [858000. 437000. 320000. 283000. 202000. 235000.]
Sales Data with Missing Values Replaced:
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [194]:
# Question 95: Missing Value Impact.

import numpy as np

total_before = np.nansum(sales_data)
sales_zero_filled = np.nan_to_num(sales_data, nan=0)
total_after = np.sum(sales_zero_filled)

print("Total Sales Before (NaNs ignored):", total_before)
print("Total Sales After (NaNs as 0):", total_after)

Total Sales Before (NaNs ignored): 11675000
Total Sales After (NaNs as 0): 11675000


In [195]:
# Question 96: Store Performance Labels.

import numpy as np

store_totals = np.sum(sales_data, axis=1)

conditions = [
    store_totals > 2800000,
    (store_totals >= 2400000) & (store_totals <= 2800000),
    store_totals < 2400000
]
labels = ["Excellent", "Good", "Needs Improvement"]

performance = np.select(conditions, labels, default="Unknown")

print("Store Totals:", store_totals)
print("Performance Labels:", performance)

Store Totals: [2270000 2295000 2310000 2820000 1980000]
Performance Labels: ['Needs Improvement' 'Needs Improvement' 'Needs Improvement' 'Excellent'
 'Needs Improvement']


In [196]:
# Question 97: Profitability Classification.

import numpy as np

profit_data = np.array([
    [50000, 250000, -20000, 120000],
    [300000, 80000, 150000, -5000],
    [90000, 220000, 60000, 180000],
    [-10000, 110000, 210000, 70000]
])

conditions = [profit_data < 0, profit_data < 100000, profit_data <= 200000, profit_data > 200000]
labels = ["Loss", "Low Profit", "Profitable", "Highly Profitable"]

print(np.select(conditions, labels, default="Unknown"))

[['Low Profit' 'Highly Profitable' 'Loss' 'Profitable']
 ['Highly Profitable' 'Low Profit' 'Profitable' 'Loss']
 ['Low Profit' 'Highly Profitable' 'Low Profit' 'Profitable']
 ['Loss' 'Profitable' 'Highly Profitable' 'Low Profit']]


# Part 18: Inventory Scenario

In [203]:
 opening_stock = np.array
 ([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

In [204]:
# Question 101: Closing Stock.

import numpy as np

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

closing_stock = opening_stock - units_sold
print("Closing Stock:\n", closing_stock)

Closing Stock:
 [[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


In [205]:
# Question 102: Low-Stock Identification.

import numpy as np

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

rows, cols = np.where(closing_stock < 30)
print("Low Stock (row,col):", list(zip(rows, cols)))

Low Stock (row,col): [(np.int64(0), np.int64(0)), (np.int64(0), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(3)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(3)), (np.int64(3), np.int64(0)), (np.int64(4), np.int64(0)), (np.int64(4), np.int64(3))]


In [206]:
# Question 103: Stock Availability Percentage.

availability_pct = (closing_stock / opening_stock) * 100
print("Availability %:\n", availability_pct)

Availability %:
 [[20.83333333 15.55555556 20.         27.77777778 24.         22.22222222]
 [22.72727273 16.         17.85714286 25.         22.22222222 22.5       ]
 [19.23076923 16.66666667 15.625      29.41176471 25.         23.52941176]
 [16.66666667 14.54545455 15.71428571 25.         21.66666667 20.45454545]
 [25.         17.5        21.15384615 26.66666667 25.         25.        ]]


In [207]:
# Question 104: Fast-Moving Products.

sold_pct = (units_sold / opening_stock) * 100
fast_rows, fast_cols = np.where(sold_pct > 80)
print("Fast Moving (row,col):", list(zip(fast_rows, fast_cols)))

Fast Moving (row,col): [(np.int64(0), np.int64(1)), (np.int64(1), np.int64(1)), (np.int64(1), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(2)), (np.int64(3), np.int64(0)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(2)), (np.int64(4), np.int64(1))]


In [208]:
# Question 105: Category-Wise Units Sold.

category_units_sold = np.sum(units_sold, axis=0)
print("Category-wise Units Sold:", category_units_sold)

Category-wise Units Sold: [ 485 1950 1240  345  980  720]


In [209]:
# Question 106: Store-Wise Units Sold.

store_units_sold = np.sum(units_sold, axis=1)
print("Store-wise Units Sold:", store_units_sold)

Store-wise Units Sold: [1110 1175 1095 1390  950]


In [210]:
# Question 107: Best Store by Unit Sales.

best_store = np.argmax(store_units_sold)
print("Best Store Index:", best_store)

Best Store Index: 3


In [211]:
# Question 108: Reorder Requirement.

reorder_matrix = closing_stock < 25
print("Reorder Matrix:\n", reorder_matrix)

Reorder Matrix:
 [[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


In [212]:
# Question 109: Reorder Quantity.

reorder_qty = np.where(closing_stock < 25, 100 - closing_stock, 0)
print("Reorder Quantity:\n", reorder_qty)

Reorder Quantity:
 [[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


# Part 19: Advanced NumPy Questions

In [213]:
# Question 110: Cumulative Store Sales.

cum_store_sales = np.cumsum(sales_data, axis=1)
print("Q110 Cumulative Store Sales:\n", cum_store_sales)


Q110 Cumulative Store Sales:
 [[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


In [214]:
# Question 111: Cumulative Company Sales.

cum_company_sales = np.cumsum(sales_data.flatten())
print("\nQ111 Cumulative Company Sales:\n", cum_company_sales)


Q111 Cumulative Company Sales:
 [  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


In [215]:
# Question 112: Sales Difference Between Categories.

category_diff = np.diff(sales_data, axis=1)
print("\nQ112 Category Sales Difference:\n", category_diff)



Q112 Category Sales Difference:
 [[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


In [216]:
# Q113: Unique Sales Values + Frequency.

unique_vals, counts = np.unique(sales_data, return_counts=True)
print("\nQ113 Unique Values:", unique_vals)
print("Frequency:", counts)



Q113 Unique Values: [ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
Frequency: [1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [217]:
# Question 114: Search for Specific Sales.

value_to_find = 420000
exists = np.any(sales_data == value_to_find)
location = np.where(sales_data == value_to_find)
print("\nQ114 Value Exists:", exists)
print("Location (row,col):", location)


Q114 Value Exists: True
Location (row,col): (array([0]), array([1]))


In [219]:
# Question 116: Clip Profit Values.

clipped_profit = np.clip(profit_data, 75000, 250000)
print("\nQ116 Clipped Profit:\n", clipped_profit)


Q116 Clipped Profit:
 [[ 75000 250000  75000 120000]
 [250000  80000 150000  75000]
 [ 90000 220000  75000 180000]
 [ 75000 110000 210000  75000]]


In [220]:
# Question 117: Normalize Sales Data.

normalized_sales = (sales_data - np.min(sales_data)) / (np.max(sales_data) - np.min(sales_data))
print("\nQ117 Normalized Sales:\n", normalized_sales)



Q117 Normalized Sales:
 [[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


In [221]:
# Question 118: Standardize Sales Data.

standardized_sales = (sales_data - np.mean(sales_data)) / np.std(sales_data)
print("\nQ118 Standardized Sales:\n", standardized_sales)



Q118 Standardized Sales:
 [[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


In [223]:
# Question 120: Save and Load Data.

np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)

loaded_sales = np.load("sales_data.npy")
loaded_cost = np.load("cost_data.npy")
loaded_profit = np.load("profit_data.npy")

print("\nQ120 Sales Match:", np.array_equal(sales_data, loaded_sales))
print("Cost Match:", np.array_equal(cost_data, loaded_cost))
print("Profit Match:", np.array_equal(profit_data, loaded_profit))


Q120 Sales Match: True
Cost Match: True
Profit Match: True
